### ISSUE TITLE
netcdf4 builds with mpich are now failing

### ISSUE THREAD

**Issue by xylar** [conda-forge/mpich-feedstock#55]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

We are seeing `mpich` build fails on `netcdf4-feedstock` with recent changes: https://github.com/conda-forge/netcdf4-feedstock/pull/112

It appears that the host environment is picking up the `external` build of the `mpich` package instead of the conda version by default.

I have found that I can get the build to work if I make `mpich-mpicc` as a dependency as well.  Before I do this, I just wanted to make sure this is the suggested solution.  It might be helpful to add some documentation for how packages with `mpich` as a dependency should handle this.  As far as I could tell, the existing documentation only tell user how to explicitly get the external version, not how to explicitly request the conda version: https://conda-forge.org/docs/user/tipsandtricks.html#using-external-message-passing-interface-mpi-libraries.  If there is already documentation on how to do this, I apologize for not finding it.

**Comment by xylar** [comment]
Here is the PR where I have added `mpich-mpicc` to make the build work: https://github.com/conda-forge/netcdf4-feedstock/pull/113

**Comment by dalcinl** [comment]
@isuruf I believe such behavior smells like a bug somewhere. Any tips for the OP?

**Comment by xylar** [comment]
Having got no feedback so far, I'm doing to go ahead with https://github.com/conda-forge/netcdf4-feedstock/pull/113.  But I do think this is something that should be investigated further if someone from @conda-forge/mpich has the time and expertise.

**Comment by isuruf** [comment]
This is probably a bug due to `current_repodata.json`. cc @mbargull

**Comment by leofang** [comment]
Likely relevant: https://gitter.im/conda-forge/conda-forge.github.io?at=6016d898ae4b9b27c18dce7c

**Comment by cekees** [comment]
It looks to me like the mpi headers aren't being installed properly. If I explicitly install mpich-mpicc, conda downgrades mpich and mpi4py in my environment to the prior release.

**Comment by sdebionne** [comment]
Could someone clarify what is the `external` build and why it is picked up by default? To get the "real" build, am I supposed to install a MPI compiler (even if I don't used them) or manually specify the build version? Installing the MPI compiler package `mpich-mpicc` reverts the compiler `gcc_linux-64` to 7.5 which is not an option, or am I doing something wrong?

**Comment by dalcinl** [comment]
@sdebionne The `external` build is a sort of dummy package that allows you to use an external build of MPICH or a derivative of it. What package version are you trying to install? With the latest package versions the `external` build should not be picked by default.

**Comment by sdebionne** [comment]
@dalcinl I try to install the latest mpich package, it turns out that I was mixing `default` (numpy) and `conda-forge` in my env and that was probably messing things up. A clean new install worked for me. Thanks for explaining the `external` build.

**Comment by zklaus** [comment]
@xylar, has this problem been addressed by #60?

**Comment by xylar** [comment]
Trying to remove the hack I put in to solve this: https://github.com/conda-forge/netcdf4-feedstock/pull/127

If that succeeds, I'll close this.

**Comment by xylar** [comment]
Indeed, this problem seems to have bee solved by #60.  Thanks very much!
