### ISSUE TITLE
4.0.2-h846660c_100 vs. 4.0.2-external_0 

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/mpich-feedstock#74]
### Comment:

I try to build a package which uses the `mpic++` command to compile:
https://github.com/conda-forge/n2p2-feedstock/pull/15

For Python 3.10 everything works fine but for Python < 3.10 the builds fail. The reason is that rather than installing `mpich=4.0.2=h846660c_100` the package `mpich=4.0.2=external_0` is installed which does not provide the corresponding executable.

**Comment by dalcinl** [comment]
Well, it actually makes sense, despite of of the fact that the external mpicc will not forward to  the conda-forge C/C++/Fortran compilers.

IMHO, the solution is to create a special mpich-mpicc-*=external* that sets the `MPICH_{CC|CXX|FC}` environment variables pointing to the conda-forge C/C++/Fortran compilers upon activation after installation within an environment. I don't know all the details, but I believe it is doable.

**Comment by jan-janssen** [comment]
I ran a couple of more tests and I had the feeling it is more or less random when the external mai package is chosen. Can I fix this in the `conda_build_config.yaml` file ? I am sorry I am not exactly sure where to set `mpich-mpicc-_=external_`

**Comment by isuruf** [comment]
This seems like a mamba bug. cc @wolfv

**Comment by wolfv** [comment]
Maybe the key is the additional `libgfortran5` dependency -- I see the CI resolves to `libgfortran4`.

**Comment by wolfv** [comment]
The blas variant with `*netlib` is depending on `libgfortran4` which pulls in the "wrong" mpich dependency.

I don't know why this recipe depends on the `netlib` implementation. Should we rebuild that package?

We could also change the sorting that is applied with track features. IIRC currently, the sorting would look like

```
mpi 4.0.2
mpi 4.0.2 external (track feature)
mpi 3.0
mpi 3.0   external (track feature)
...
```

We could instead use

```
mpi 4.0.2 
mpi 3.0
mpi 4.0.2 external (track feature)
mpi 3.0   external (track feature)
```

So that the algorithm would try older non-external versions first...

```
libblas 3.8.0 10_h6e990d7_netlib
--------------------------------
file name   : libblas-3.8.0-10_h6e990d7_netlib.tar.bz2
name        : libblas
version     : 3.8.0
build       : 10_h6e990d7_netlib
build number: 10
size        : 175 KB
license     : BSD 3-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/t/wo-3b33cb09-bcc1-4bd5-b2fb-83d62214c090/conda-forge/linux-64/libblas-3.8.0-10_h6e990d7_netlib.tar.bz2
md5         : 9b6100f5e76dcc1dfb59ee07a61569db
track features: blas_netlib
timestamp   : 2020-10-11 17:00:49 UTC
dependencies:
  - libgfortran-ng
  - libgcc-ng >=7.5.0
  - libgfortran4 >=7.5.0
```

**Comment by isuruf** [comment]
AFAIK, the second sorting option is the one that conda implements.

**Comment by wolfv** [comment]
in that case, mamba would resolve to mpich 3.3.2 which seems to be pretty old and just as "surprising".

Just wondering if it is possible to rebuild the netlib blas for libgfortran5?

I'll take a note of the sorting order of variants with track features.

**Comment by jan-janssen** [comment]
> Could it be possible that those conflict somehow with the rest of the recipe?

Currently the requirements are: 
```
    - python
    - cython
    - {{ mpi }}
    - libblas
    - libcblas
    - gsl
    - eigen
```
 So I do not directly see the reason why it aims for `libgfortran4`. 

The other thing I noticed is that when I restart the build sometimes some of the failing builds work but it is rather random. 

Is there anything I can do to enforce the choice of the internal mpich?

**Comment by jan-janssen** [comment]
Can I enforce the use of `mpich` internal in `conda_build_config.yaml`?

**Comment by jan-janssen** [comment]
@isuruf  I saw you rerendered the recipe and now it works. Does this mean the issue is resolved? I do not really understand what exactly changed.

**Comment by jan-janssen** [comment]
Ok, it seems to be the difference between `netlike 3.8` and `3.9`

**Comment by isuruf** [comment]
Yes, `netlib 3.8` had two builds (one for `libgfortran4` and one for `libgfortran5`). mamba was getting confused by that.
changing to `3.9` which has only one build makes mamba less confused.
