### ISSUE TITLE
[PERF] mpich from conda-forge is slower enough against mpich from PyPI

### ISSUE THREAD

**Issue by YarShev** [conda-forge/mpich-feedstock#80]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I tried MPICH both from PyPI ([mpi4py-mpich](https://pypi.org/project/mpi4py-mpich/)) and from conda-forge. MPICH from conda-forge is slower enough against MPICH from PyPI. As far as I know, MPICH supports XPMEM for 1-copy interprocess communication, which should be enabled by default. Might be that the case that MPICH has a build issue in conda-forge similar to one OpenMPI has regarding CMA in https://github.com/conda-forge/openmpi-feedstock/issues/118?

cc @dalcinl 

### Installed packages

```shell
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1
libffi                    3.4.2                h6a678d5_6
libgcc-ng                 11.2.0               h1234567_1
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.1.4            py38hfc96bbd_0
mpich                     3.3.2                hc856adb_0
ncurses                   6.4                  h6a678d5_0
openssl                   1.1.1t               h7f8727e_0
pip                       23.0.1           py38h06a4308_0
python                    3.8.16               h7a1cb2a_3
readline                  8.2                  h5eee18b_0
setuptools                65.6.3           py38h06a4308_0
sqlite                    3.41.2               h5eee18b_0
tk                        8.6.12               h1ccaba5_0
wheel                     0.38.4           py38h06a4308_0
xz                        5.2.10               h5eee18b_1
zlib                      1.2.13               h5eee18b_0
```

### Environment info

```shell
active environment : mpich
    active env location : $CONDA_PATH/envs/mpich
            shell level : 1
       user config file : $HOME_PATH/.condarc
 populated config files :
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.8.13.final.0
       virtual packages : __cuda=12.0=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : $CONDA_PATH  (writable)
      conda av data dir : $CONDA_PATH/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : $CONDA_PATH/pkgs
                          $HOME_PATH/.conda/pkgs
       envs directories : $CONDA_PATH/envs
                          $HOME_PATH/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.8.13 Linux/5.4.0-136-generic ubuntu/20.04.4 glibc/2.31
                UID:GID : 11815093:22002
             netrc file : None
           offline mode : False
```

**Comment by dalcinl** [comment]
I'm not responsible from the `mpi4py-mpich` package from PyPI, this package was upload by bodo.ai, and I do endorse nor agree with what they did. Rather than running a private PyPI server to fulfill their needs, this company decided to "pollute" the public PyPI namespace with a build of their own that they do not care to keep up to date (mpi4py not latest, bundled MPICH not latest). They do not even care of updating the package metadata, and they list Lisandro as the maintainer!

Regarding the MPICH from conda-forge, I would be not surprised that the issue is similar to CMA with Open MPI. 
XPMEM is a kernel module, and most likely that module is not available in the constrained build environment of conda-forge packages. You should ask MPICH developers about it for a confirmation.

@YarShev If you care about ultimate performance, you should build your backend MPI yourself, and not rely on conda-forge packages (they are built for compatibility rather than performance). Perhaps even better, you can try building the conda-forge recipe locally, and upload the generated artifacts to your own channel within anaconda.org.

**Comment by YarShev** [comment]
@dalcinl, oh, I see, thanks for your response. Do you think it would be good to add a note in mpi4py docs regarding building own backend MPI by users and not rely on conda-forge or PyPI packages if the users care about ultimate performance? Or maybe there is already a related note in the docs?

**Comment by dalcinl** [comment]
Are you aware that conda-forge have special documentation about MPI? These docs discuss how to use conda-forge packages with an "external" MPI build [[link]](https://conda-forge.org/docs/user/tipsandtricks.html#using-external-message-passing-interface-mpi-libraries). I would argue that adding a note there would be more appropriate, as the performance issue affects all MPI-based libraries, not only mpi4py. The first paragraph gives some rationale for using external MPI, ultimate performance is just another rationale to go that way. I guess you can submit a quick PR to enhance these docs, maybe mentioning the lack or XPMEM and/or CMA.

**Comment by YarShev** [comment]
@dalcinl, just to let you know, my PR has been merged.

**Comment by dalcinl** [comment]
See mpi4py/mpi4py#348.

**Comment by YarShev** [comment]
@dalcinl, why did you close the issue? Do you think that this issue will never be fixed?

**Comment by dalcinl** [comment]
Well, I do not like keeping issues open when I'm not going to take any particular action on it. However, this feedstock repository is not my private playground, so you are right, I should have not close this issue.

**Comment by YarShev** [comment]
As part of our work on unidist we did measurements for 1. mpich (4.0.1 and 4.1.1) built from source, 2. mpich (4.0.1 and 4.1.1) from conda-forge. It looks like mpich=4.0.1 from source and from conda shows more or less similar timings in comparison to each other. Same is true for mpich=4.1.1. However, there is a decent slowdown in mpich=4.1.1 against mpich=4.0.1.

Is anyone aware of a performance issue in mpich=4.1.1 against mpich=4.0.1?

**Comment by dalcinl** [comment]
@YarShev You should probably submit an issue to [pmodels/mpich](https://github.com/pmodels/mpich/issues/new) and report your findings there. Maybe @hzhou can drop a quick comment here.

**Comment by YarShev** [comment]
https://github.com/pmodels/mpich/issues/6541
