### ISSUE TITLE
mpich 4.2.0

### ISSUE THREAD

**Issue by folmos-at-orange** [conda-forge/mpich-feedstock#91]
### Comment:

Hello, are there any plans to release the newest mpich 4.2.0 ?

Thanks.

**Comment by dalcinl** [comment]
@folmos-at-orange As soon as the bot submits the PR for the version update, we will deal with it. 

@leofang @minrk I will need your input here. This version of MPICH adds support for the MPI 4.1 standard. The MPI header and library is API and ABI backward compatible, but there are new symbols in the MPI library. Therefore, I believe this will have to update our pining to `x.x` or something like that. I will need help to figure out the exact change.

**Comment by leofang** [comment]
The current `run_exports` is already correct. If there's any package built against mpich 4.2.0, it'd get a run dependency `- mpich >=4.2,<5` so no problem would happen even if the package uses any new symbol.

**Comment by dalcinl** [comment]
Oh, now I know why the bot had not issued the update PR yet. We have a hack in meta.yml to support the old MPICH version scheme that did not include the final ".0" in "x.y" releases. After my request, now they use proper semantic versioning, thus "x.y.0". We have to fix the recipe first for the bot to run successfully.

**Comment by dalcinl** [comment]
Manual update PR at #92.

**Comment by folmos-at-orange** [comment]
Thanks for the release.
